name: API Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: pytest -k smoke --html=results/report.html
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: api-test-report
          path: results/
          retention-days: 30